dist: xenial
language: python
python: 3.7.4
install:
  - pip install pipenv
  - pipenv install
script:
  - pytest --cov=PyFynance
  - black --check .
  - behave ./test/behave
after_success:
  - coveralls
